--- #YAML:1.0
name:                     CPAN-Testers-WWW-Reports-Mailer
version:                  0.19
abstract:                 CPAN Testers Reports Mailer
author:
  - Barbie <barbie@cpan.org>

license:                  perl
distribution_type:        module
installdirs:              site

requires:
  Compress::Zlib:                   0
  Config::IniFiles:                 0
  Class::Accessor::Fast:            0
  CPAN::Testers::Common::DBUtils:   0.03
  Email::Address:                   0
  Email::Simple:                    0
  File::Basename:                   0
  File::Slurp:                      0
  Getopt::ArgvFile:                 0
  Getopt::Long:                     0
  LWP::UserAgent:                   0
  MIME::Base64:                     0
  MIME::QuotedPrint:                0
  Path::Class:                      0
  Parse::CPAN::Authors:             0
  Template:                         0
  Time::Piece:                      0
  DBD::mysql:                       0
  DBD::SQLite:                      1.07
  version:                          0

provides:
  CPAN::Testers::WWW::Reports::Mailer:
    file:     lib/CPAN/Testers/WWW/Reports/Mailer.pm
    version:  0.19

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
