--- #YAML:1.0
name:                     CPAN-Testers-WWW-Reports-Mailer
version:                  0.31
abstract:                 CPAN Testers Reports Mailer
author:
  - Barbie <barbie@cpan.org>

license:                  artistic_2
distribution_type:        module
installdirs:              site

requires:
  perl:                           5.006
  Compress::Zlib:                 0
  Config::IniFiles:               0
  Class::Accessor::Fast:          0
  CPAN::Testers::Common::DBUtils: 0.03
  CPAN::Testers::Common::Utils:   0
  DBI:                            0
  DBD::mysql:                     0
  Email::Address:                 0
  Email::Simple:                  0
  File::Basename:                 0
  File::Path:                     0
  File::Slurp:                    0
  Getopt::ArgvFile:               0
  Getopt::Long:                   0
  LWP::UserAgent:                 0
  MIME::Base64:                   0
  MIME::QuotedPrint:              0
  Path::Class:                    0
  Parse::CPAN::Authors:           0
  Template:                       0
  Time::Piece:                    0
  version:                        0
recommends:
  Test::CPAN::Meta:               0
  Test::CPAN::Meta::JSON:         0
  Test::Database:                 0
  Test::Pod:                      1.00
  Test::Pod::Coverage:            0.08
build_requires:
  IO::File:                       0
  Test::More:                     0.70
  Test::Trap:                     0

provides:
  CPAN::Testers::WWW::Reports::Mailer:
    file:     lib/CPAN/Testers/WWW/Reports/Mailer.pm
    version:  0.31

resources:
  license:    http://www.perlfoundation.org/artistic_license_2_0
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=CPAN-Testers-WWW-Reports-Mailer
  repository: git://github.com/barbie/cpan-testers-www-reports-mailer.git

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
